### ISSUE TITLE
Error when trying to use canUndo canRedo buttons

### ISSUE THREAD

**Issue by digoburigo** [nilsmehlhorn/ngrx-wieder#34] opened 2021-03-23 18:46 UTC
Hello,

I have some error when i tried to use the canUndo and canRedo selectors
The error on the image occurs

I can share my state code if necessary

![image](https://user-images.githubusercontent.com/28462822/112201085-aadcb380-8bee-11eb-88b2-55f5216b65aa.png)

**Comment by nilsmehlhorn** [comment] 2021-03-24 15:22
Hey, yes please share your code or - even better- provide a reproduction on StackBlitz or similar :)

**Comment by nilsmehlhorn** [comment] 2021-04-12 11:30
Closing because of inactivity

**Comment by digoburigo** [comment] 2021-04-20 14:08
Hello, sorry for the late response
But here it is in CodeSandbox https://codesandbox.io/s/quizzical-ganguly-r61nr?file=/src/app/map-buttons/view-buttons/next.component.ts

**Comment by nilsmehlhorn** [comment] 2021-04-23 09:58
Your reproduction logs errors to the console, running it locally made them readable:
```bash
ERROR TypeError: state.histories is undefined
    selectHistory ngrx-wieder.js:179
    ...
````

That's because you didn't select your feature state properly:
```diff
// state-view/map-view.selectors.ts
+ import * as fromRoot from '../reducers';

- const selectFeature = (state: fromView.State) => state;
+ const selectFeature = (state: fromRoot.State) => state.view;
export const {
  selectHistory,
  selectCanUndo,
  selectCanRedo,
- } = createHistorySelectors<any, fromView.State>(selectFeature);
+ } = createHistorySelectors<fromRoot.State, fromView.State>(selectFeature);
```

A feature selector usually receives the root state and returns the feature slice. You are just returning the base state again which doesn't have the `histories` property. Including the NgRx's Devtools might make this easier to see.

Also, you'll have to type the store with the root state in your components or facades:
```diff
// state-view/map-view.facade.ts
+ import * as fromRoot from "../reducers";

export class MapViewFacade {
  zoom$ = this.store.pipe(select(MapViewSelectors.selectZoom));
  center$ = this.store.pipe(select(MapViewSelectors.selectCenter));

  canUndo$ = this.store.pipe(select(MapViewSelectors.selectCanUndo));

  canRedo$ = this.store.pipe(select(MapViewSelectors.selectCanRedo));

-  constructor(private store: Store<fromView.State>) {}
+  constructor(private store: Store<fromRoot.State>) {}

}
```

After fixing those points, the app runs without errors for me and the selectors seem to work. I can't tell if the functionality is what you want it to be, however, looking at the DevTools, the state seems to update properly. :slightly_smiling_face:

**Comment by digoburigo** [comment] 2021-04-23 12:46
Oh I see, in CodeSandbox I fixed using this changes and it works. Thanks.
Other topic, when the undo/redo action it's dispatched the state it's updated again because I'm listening to the map event "move end", so the behavior it's not the ideal. Do you have a tip on how to solve this issue, like maybe put a flag saying that the move end it's caused by the undo/redo actions or something like that?

**Comment by nilsmehlhorn** [comment] 2021-04-23 14:41
Closing since the original issue has been resolved

> Other topic, when the undo/redo action it's dispatched the state it's updated again because I'm listening to the map event "move end", so the behavior it's not the ideal. Do you have a tip on how to solve this issue, like maybe put a flag saying that the move end it's caused by the undo/redo actions or something like that?

It's really hard for me to understand what you're trying to do because you provide very few information. If you want to do something based on when a specific action is undone/redone, you can write an effect as shown here https://github.com/nilsmehlhorn/ngrx-wieder/pull/29#issuecomment-766395498

**Closed by nilsmehlhorn** 2021-04-23 14:41 UTC
Labels: invalid, question
